---
# Main config

- hosts: dedibox
  remote_user: root
  roles:
  - common
  vars_prompt:
  - name: "hostname"
    prompt: "Hostname"
  - name: "ipaddr"
    prompt: "IPv4"
  - name: "geli_pwd"
    prompt: "GELI passphrase"
    private: yes
