---
# Install base distribution files

- name: Get dists files
  get_url: url="{{ base_url }}/{{ item }}.txz" dest="/tmp"
  with_items: dists
- name: Extract distribution files
  command: "tar -C /{{ rootfs }} -xjf /tmp/{{ item }}.txz"
  with_items: dists
