---
# GELI partition management

- name: Save passphrase
  vars_prompt:
    - name: "geli_pwd"
      prompt: "GELI passphrase"
      private: yes
  shell: echo {{ geli_pwd }} >{{ passfile }}
    creates="{{ passfile }}"
- name: Create GELI parts
  command: geli init -b -K /root/keys/boot.key -J {{ passfile }} -s 4096 -l 256 gpt/{{ pool }}{{ item }}
    creates="/dev/gpt/{{ pool }}{{ item }}.eli"
  with_items: disks
- name: Attach GELI parts
  command: geli attach  -j {{ passfile }} -k /root/keys/boot.key gpt/{{ pool }}{{ item }}
  with_items: disks
- name: Remove passfile
  command: rm -f {{ passfile }}
  