---
# Kernel modules loading

- name: Fetch missing kernel modules
  get_url: url="{{ base_url }}/kernel.txz" dest="/tmp/"
- name: Extract modules
  command: tar -C /tmp -xjf /tmp/kernel.txz
    creates="/tmp/boot/kernel/kernel"
- name: Load various needed modules
  command: kldload -n -q /tmp/boot/kernel/{{ item }}.ko
  with_items: kmods
