---
# Define the overall set of tasks

- include: kernel.yml
- include: part.yml
- include: disk.yml
- include: keys.yml
- include: geli.yml
- include: pools.yml
- include: swap.yml
- include: fs.yml
- include: dists.yml
- include: config.yml
