---
# Define the overall set of tasks

- include: kernel.yml
- include: dinit.yml
- include: disk.yml
- include: keys.yml
- include: geli.yml
  vars_prompt:
    - name: "geli_pwd"
      prompt: "GELI passphrase"
      private: yes
- include: pools.yml
- name: Create mirror for swap
  command: gmirror label swap gpt/swap0 gpt/swap1
- name: Set checksum
  command: zfs set checksum=fletcher4 {{ item }}
  with_items:
    - bpool
    - pool
- name: Create FS on tank
  command: echo creating {{ item }}
  with_items:
    - fs
    - svfs
    - tfs
- name: Extract dists
  command: echo dists
- name: Fixup config
  command: echo config
