---
# Define the overall set of tasks

- include: kernel.yml
- include: part.yml
- include: disk.yml
- include: keys.yml
- include: geli.yml
  vars_prompt:
    - name: "geli_pwd"
      prompt: "GELI passphrase"
      private: yes
- include: pools.yml
- include: swap.yml
- include: fs.yml
- include: dists.yml
- include: config.yml
  vars_prompt:
    - name: "hostname"
      prompt: "Hostname"
    - name: "ipaddr"
      prompt: "IPv4"
