---
# Variables

release: "9.2-RELEASE"
disk: "da"
disks:
- 0
- 1
kmods:
- "crypto"
- "aesni"
- "geom_eli"
- "geom_mirror"
- "zfs"
kurl: "ftp://ftp.fr.freebsd.org/pub/FreeBSD/releases/amd64/amd64/{{ release }}/kernel.txz"
passfile: "/tmp/geli_pwd"
bpool: "zboot"
lpool: "boot"
pool: "tank"
compression: "lz4"
rootfs: "{{ pool }}/root"
basefs:
- "usr"
- "var"
- "home"
- "jails"
- "home/staff"
- "usr/local"
- "usr/ports"
- "usr/src"
- "var/db"
- "var/db/pkg"
- "var/log"
spfs:
- "var/empty"
- "var/named"
- "var/run"
tmpfs:
- "tmp"
- "var/tmp"
nocompfs:
- "usr/ports/distfiles"
- "usr/ports/packages"
dists:
- base
- doc
- games
- kernel
- lib32
