---
# Post-installation configuration

- name: Configure loader.conf
  template: src=loader.conf.j2
      dest="/{{ rootfs }}/boot/loader.conf" owner=0 group=0 mode=0644
- name: Configure rc.conf
  template: src=rc.conf.j2
      dest="/{{ rootfs }}/etc/rc.conf" owner=0 group=0 mode=0644
- name: Configure sysctl.conf
  template: src=sysctl.conf.j2
      dest="/{{ rootfs }}/etc/sysctl.conf" owner=0 group=0 mode=0644
- name: Configure fstab
  template: src=fstab.j2
      dest="/{{ rootfs }}/etc/fstab" owner=0 group=0 mode=0644
